/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.CreateImage;
import DTO.*;
import BUS.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author voota
 */
public class JPanelSupplier extends javax.swing.JPanel {

    /**
     * Creates new form JPanelQuanLyNhanVien
     */
    private ListSupplier listSp;
    private SupplierBUS splBUS;
    private int selectedRowIndex;
    private boolean flat;

    public boolean isFlat() {
        return flat;
    }

    public JPanelSupplier() {
        initComponents();
        init();
        editDisplay();
        this.setSize(960, 700);
        this.setVisible(true);
    }

    public final void editDisplay() {
        CreateImage cre = new CreateImage();
        cre.changeColorButton(buttonAdd);
        cre.changeColorButton(buttonFix);
        cre.changeColorButton(buttonSearchSupplier);
        cre.changeColorButton(buttonShowAll);
        cre.setIconForButton(buttonAdd, "add.png");
        cre.setIconForButton(buttonFix, "fix.png");
        cre.setIconForButton(buttonSearchSupplier, "search.png");
        cre.setIconForButton(buttonShowAll, "refesh.png");
        labelPictureSupplier.setSize(200, 200);
        cre.setIconForLabel(labelPictureSupplier, "labelPictureSupplier.png");
    }

    private void init() {
        listSp = new ListSupplier();
        splBUS = new SupplierBUS(listSp, this);
        buttonAdd.addActionListener(splBUS);
        buttonFix.addActionListener(splBUS);
        buttonShowAll.addActionListener(splBUS);
        buttonSearchSupplier.addActionListener(splBUS);

        setSupplier();
        showList(listSp.getList());
    }

    public javax.swing.JButton getButtonAdd() {
        return buttonAdd;
    }

    public javax.swing.JButton getButtonFix() {
        return buttonFix;
    }

    public javax.swing.JButton getButtonSearchSupplier() {
        return buttonSearchSupplier;
    }

    public javax.swing.JButton getButtonShowAll() {
        return buttonShowAll;
    }

    public javax.swing.JTable getJTableSupplier() {
        return jTableSupplier;
    }

    public javax.swing.JLabel getLabelPictureSupplier() {
        return labelPictureSupplier;
    }

    public javax.swing.JTextField getTextFieldSearch() {
        return textFieldSearch;
    }

    public javax.swing.JTextField getTextFieldSupplierAddress() {
        return textFieldSupplierAddress;
    }

    public javax.swing.JTextField getTextFieldSupplierID() {
        return textFieldSupplierID;
    }

    public javax.swing.JTextField getTextFieldSupplierName() {
        return textFieldSupplierName;
    }

    public javax.swing.JTextField getTextFieldSupplierNumberPhone() {
        return textFieldSupplierNumberPhone;
    }

    private void setSupplier() {
        jTableSupplier.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selectedRowIndex = jTableSupplier.getSelectedRow();
                showInfo();
            }
        });
    }
    
    private void showInfo(){
                splBUS.setEnabled(false);
                textFieldSupplierID.setText(jTableSupplier.getValueAt(selectedRowIndex, 0).toString());
                textFieldSupplierName.setText(jTableSupplier.getValueAt(selectedRowIndex, 1).toString());
                textFieldSupplierAddress.setText(jTableSupplier.getValueAt(selectedRowIndex, 2).toString());
                textFieldSupplierNumberPhone.setText(jTableSupplier.getValueAt(selectedRowIndex, 3).toString());
    }

    public void showList(ArrayList<SupplierDTO> list) {
        DefaultTableModel supplierTable = (DefaultTableModel) jTableSupplier.getModel();
        supplierTable.setRowCount(0);
        if (list == null) {
            return;
        }
        for (SupplierDTO splDTO : list) {
            supplierTable.addRow(new Object[]{splDTO.getSupplierID(), splDTO.getName(), splDTO.getAddress(), splDTO.getPhone()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonFix = new javax.swing.JButton();
        buttonShowAll = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldSupplierNumberPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldSupplierAddress = new javax.swing.JTextField();
        textFieldSupplierName = new javax.swing.JTextField();
        labelPictureSupplier = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textFieldSupplierID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textFieldSearch = new javax.swing.JTextField();
        buttonSearchSupplier = new javax.swing.JButton();
        scrollPane2 = new java.awt.ScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSupplier = new javax.swing.JTable();

        buttonAdd.setForeground(new java.awt.Color(0, 0, 0));
        buttonAdd.setText("Thêm");
        buttonAdd.setBorderPainted(false);

        buttonFix.setForeground(new java.awt.Color(0, 0, 0));
        buttonFix.setText("Sửa");
        buttonFix.setBorderPainted(false);

        buttonShowAll.setForeground(new java.awt.Color(0, 0, 0));
        buttonShowAll.setText("Làm mới");
        buttonShowAll.setBorderPainted(false);
        buttonShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFix, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nhà cung cấp");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Địa chỉ");

        textFieldSupplierNumberPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldSupplierNumberPhoneFocusLost(evt);
            }
        });
        textFieldSupplierNumberPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSupplierNumberPhoneActionPerformed(evt);
            }
        });
        textFieldSupplierNumberPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldSupplierNumberPhoneKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tên nhà cung cấp");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Số điện thoại");

        textFieldSupplierAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSupplierAddressActionPerformed(evt);
            }
        });
        textFieldSupplierAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldSupplierAddressKeyReleased(evt);
            }
        });

        textFieldSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSupplierNameActionPerformed(evt);
            }
        });
        textFieldSupplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldSupplierNameKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Mã nhà cung cấp");

        textFieldSupplierID.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldSupplierNumberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(labelPictureSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFieldSupplierID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(textFieldSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(textFieldSupplierNumberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelPictureSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tìm kiếm");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        textFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSearchActionPerformed(evt);
            }
        });
        jPanel3.add(textFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 720, 30));

        buttonSearchSupplier.setForeground(new java.awt.Color(0, 0, 0));
        buttonSearchSupplier.setText("Tìm kiếm");
        buttonSearchSupplier.setBorderPainted(false);
        buttonSearchSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchSupplierActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSearchSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 120, 46));

        jTableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Số điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableSupplierKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTableSupplier);

        scrollPane2.add(jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldSupplierAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSupplierAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSupplierAddressActionPerformed

    private void textFieldSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSupplierNameActionPerformed

    private void textFieldSupplierNumberPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSupplierNumberPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSupplierNumberPhoneActionPerformed

    private void buttonSearchSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchSupplierActionPerformed

    private void buttonShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonShowAllActionPerformed

    private void textFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSearchActionPerformed

    private void textFieldSupplierAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldSupplierAddressKeyReleased
        String address = textFieldSupplierAddress.getText().trim();

        if (address.isEmpty()) {
            return;
        }

        if (address.length() > 200) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Địa chỉ của nhà cung cấp không hợp lệ");
            textFieldSupplierAddress.setText("");
            textFieldSupplierAddress.requestFocus();
            flat = false;
        }
    }//GEN-LAST:event_textFieldSupplierAddressKeyReleased

    private void textFieldSupplierNumberPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldSupplierNumberPhoneKeyReleased
    }//GEN-LAST:event_textFieldSupplierNumberPhoneKeyReleased

    private void textFieldSupplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldSupplierNameKeyReleased
        String supplierName = textFieldSupplierName.getText().trim();

        if (supplierName.isEmpty()) {
            return;
        }

        if (!Tool.isName(supplierName)) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp không hợp lệ");
            textFieldSupplierName.setText("");
            textFieldSupplierName.requestFocus();
            flat = false;
        } else if (!listSp.checkNameExist(supplierName)) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp này đã được sử dụng.", "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            textFieldSupplierNumberPhone.setText("");
            textFieldSupplierName.requestFocus();
            flat = false;
        }
    }//GEN-LAST:event_textFieldSupplierNameKeyReleased

    private void textFieldSupplierNumberPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldSupplierNumberPhoneFocusLost
        String phone = textFieldSupplierNumberPhone.getText().trim();

        if (phone.isEmpty()) {
            return;
        }

        if (!Tool.checkPhone(phone)) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng số điện thoại.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            textFieldSupplierNumberPhone.setText("");
            textFieldSupplierNumberPhone.requestFocus();
            flat = false;
        } else if (!listSp.checkPhoneExist(phone)) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Số điện thoại này đã được sử dụng.", "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            textFieldSupplierNumberPhone.setText("");
            textFieldSupplierNumberPhone.requestFocus();
            flat = false;
        }
    }//GEN-LAST:event_textFieldSupplierNumberPhoneFocusLost

    private void jTableSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableSupplierKeyPressed
        selectedRowIndex = jTableSupplier.getSelectedRow();
        int rowCount = jTableSupplier.getRowCount();

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP -> {
                if (selectedRowIndex > 0) {
                    jTableSupplier.changeSelection(selectedRowIndex--, 0, false, false);
                } else {
                }
            }
            case KeyEvent.VK_DOWN -> {
                if (selectedRowIndex == rowCount - 1) {
                } else {
                    jTableSupplier.changeSelection(selectedRowIndex++, 0, false, false);
                }
            }
        }
        showInfo();
    }//GEN-LAST:event_jTableSupplierKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonFix;
    private javax.swing.JButton buttonSearchSupplier;
    private javax.swing.JButton buttonShowAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableSupplier;
    private javax.swing.JLabel labelPictureSupplier;
    private java.awt.ScrollPane scrollPane2;
    private javax.swing.JTextField textFieldSearch;
    private javax.swing.JTextField textFieldSupplierAddress;
    private javax.swing.JTextField textFieldSupplierID;
    private javax.swing.JTextField textFieldSupplierName;
    private javax.swing.JTextField textFieldSupplierNumberPhone;
    // End of variables declaration//GEN-END:variables
}
