/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.CreateImage;
import javax.swing.table.DefaultTableModel;
import DTO.*;
import BUS.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author voota
 */
public class JPanelDiscount extends javax.swing.JPanel {

    /**
     * Creates new form JPanelQuanLyNhanVien
     */
    private ListDiscount listDc;
    private DiscountBUS dcBUS;
    private int selectedRowIndex;
    private boolean flat;

    public JPanelDiscount() {
        initComponents();
        init();
        editDisplay();
        this.setSize(960, 700);
        this.setVisible(true);
    }

    private void init() {
        listDc = new ListDiscount();
        dcBUS = new DiscountBUS(listDc, this);
        buttonAdd.addActionListener(dcBUS);
        buttonFix.addActionListener(dcBUS);
        buttonShowAll.addActionListener(dcBUS);
        buttonSearchDiscount.addActionListener(dcBUS);

        setDiscount();
        showList(listDc.getList());
    }

    public boolean isFlat() {
        return flat;
    }

    public javax.swing.JButton getButtonAdd() {
        return buttonAdd;
    }

    public javax.swing.JButton getButtonFix() {
        return buttonFix;
    }

    public javax.swing.JButton getButtonSearchDiscount() {
        return buttonSearchDiscount;
    }

    public javax.swing.JButton getButtonShowAll() {
        return buttonShowAll;
    }

    public javax.swing.JTable getJTableDiscount() {
        return jTableDiscount;
    }

    public javax.swing.JLabel getLabelPictureDiscount() {
        return labelPictureDiscount;
    }

    public javax.swing.JTextField getTextFieldContent() {
        return textFieldContent;
    }

    public javax.swing.JTextField getTextFieldDiscountEndDay() {
        return textFieldDiscountEndDay;
    }

    public javax.swing.JTextField getTextFieldDiscountID() {
        return textFieldDiscountID;
    }

    public javax.swing.JTextField getTextFieldDiscountName() {
        return textFieldDiscountName;
    }

    public javax.swing.JTextField getTextFieldDiscountStartDay() {
        return textFieldDiscountStartDay;
    }

    public javax.swing.JTextField getTextFieldSearch() {
        return textFieldSearch;
    }

    public final void editDisplay() {
        CreateImage cre = new CreateImage();
        cre.changeColorButton(buttonAdd);
        cre.changeColorButton(buttonFix);
        cre.changeColorButton(buttonSearchDiscount);
        cre.changeColorButton(buttonShowAll);
        cre.setIconForButton(buttonAdd, "add.png");
        cre.setIconForButton(buttonFix, "fix.png");
        cre.setIconForButton(buttonSearchDiscount, "search.png");
        cre.setIconForButton(buttonShowAll, "refesh.png");
        labelPictureDiscount.setSize(350, 200);
        cre.setIconForLabel(labelPictureDiscount, "labelPictureDiscount.png");
    }

    private void setDiscount() {
        jTableDiscount.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selectedRowIndex = jTableDiscount.getSelectedRow();
                if (selectedRowIndex != -1) {
                    showInfo();
                }
            }
        });
    }

    private void showInfo() {
        dcBUS.setEnabled(false);
        textFieldDiscountID.setText(jTableDiscount.getValueAt(selectedRowIndex, 0).toString());
        textFieldDiscountName.setText(jTableDiscount.getValueAt(selectedRowIndex, 1).toString());
        textFieldContent.setText(jTableDiscount.getValueAt(selectedRowIndex, 2).toString());
        textFieldDiscountStartDay.setText(jTableDiscount.getValueAt(selectedRowIndex, 3).toString());
        textFieldDiscountEndDay.setText(jTableDiscount.getValueAt(selectedRowIndex, 4).toString());
    }

    public void showList(ArrayList<DiscountDTO> list) {
        DefaultTableModel discountTable = (DefaultTableModel) jTableDiscount.getModel();
        discountTable.setRowCount(0);
        if (list == null) {
            return;
        }
        for (DiscountDTO dcDTO : list) {
            discountTable.addRow(new Object[]{dcDTO.getDiscountID(), dcDTO.getDiscountName(), dcDTO.getPercentDiscount(), dcDTO.getBegin(), dcDTO.getEnd()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldDiscountName = new javax.swing.JTextField();
        textFieldDiscountStartDay = new javax.swing.JTextField();
        textFieldDiscountEndDay = new javax.swing.JTextField();
        textFieldContent = new javax.swing.JTextField();
        textFieldDiscountID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonFix = new javax.swing.JButton();
        buttonShowAll = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textFieldSearch = new javax.swing.JTextField();
        buttonSearchDiscount = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        scrollPane2 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDiscount = new javax.swing.JTable();
        labelPictureDiscount = new javax.swing.JLabel();

        jLabel3.setText("Tên chương trình");

        jLabel4.setText("Ngày bắt đầu(dd/MM/yyyy)");

        jLabel5.setText("Ngày kết thúc(dd/MM/yyyy)");

        jLabel6.setText("Phần trăm giảm giá");

        textFieldDiscountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDiscountNameActionPerformed(evt);
            }
        });
        textFieldDiscountName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldDiscountNameKeyReleased(evt);
            }
        });

        textFieldDiscountStartDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldDiscountStartDayFocusLost(evt);
            }
        });
        textFieldDiscountStartDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDiscountStartDayActionPerformed(evt);
            }
        });
        textFieldDiscountStartDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldDiscountStartDayKeyReleased(evt);
            }
        });

        textFieldDiscountEndDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldDiscountEndDayFocusLost(evt);
            }
        });
        textFieldDiscountEndDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDiscountEndDayActionPerformed(evt);
            }
        });
        textFieldDiscountEndDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldDiscountEndDayKeyReleased(evt);
            }
        });

        textFieldContent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldContentFocusLost(evt);
            }
        });
        textFieldContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldContentActionPerformed(evt);
            }
        });
        textFieldContent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldContentKeyReleased(evt);
            }
        });

        textFieldDiscountID.setEnabled(false);

        jLabel1.setText("Mã khuyến mãi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldContent, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(textFieldDiscountEndDay)
                    .addComponent(textFieldDiscountStartDay)
                    .addComponent(textFieldDiscountName)
                    .addComponent(textFieldDiscountID))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDiscountID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(textFieldDiscountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldDiscountStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldDiscountEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20))
        );

        buttonAdd.setForeground(new java.awt.Color(0, 0, 0));
        buttonAdd.setText("Thêm");
        buttonAdd.setBorderPainted(false);

        buttonFix.setForeground(new java.awt.Color(0, 0, 0));
        buttonFix.setText("Sửa");
        buttonFix.setBorderPainted(false);

        buttonShowAll.setForeground(new java.awt.Color(0, 0, 0));
        buttonShowAll.setText("Làm mới");
        buttonShowAll.setBorderPainted(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonFix, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tìm kiếm");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        textFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSearchActionPerformed(evt);
            }
        });
        jPanel3.add(textFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 670, 30));

        buttonSearchDiscount.setForeground(new java.awt.Color(0, 0, 0));
        buttonSearchDiscount.setText("Tìm kiếm");
        buttonSearchDiscount.setBorderPainted(false);
        buttonSearchDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchDiscountActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSearchDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 150, 46));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Thông tin khuyến mãi");

        jTableDiscount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên chương trình", "Phần trăm giảm giá", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableDiscountKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDiscount);

        scrollPane2.add(jScrollPane2);

        labelPictureDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPictureDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPictureDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDiscountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDiscountNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDiscountNameActionPerformed

    private void textFieldDiscountStartDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDiscountStartDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDiscountStartDayActionPerformed

    private void textFieldDiscountEndDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDiscountEndDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDiscountEndDayActionPerformed

    private void textFieldContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldContentActionPerformed

    private void textFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSearchActionPerformed

    private void buttonSearchDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchDiscountActionPerformed

    private void textFieldDiscountNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldDiscountNameKeyReleased
        String discountName = textFieldDiscountName.getText().trim();

        if (discountName.isEmpty()) {
            return;
        }

        if (discountName.length() > 200) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Tên khuyến mãi không hợp lệ.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            flat = false;
            textFieldDiscountName.requestFocus();
            textFieldDiscountName.setText("");
        } else if (!listDc.checkNameExist(discountName)) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Tên khuyến mãi này đã được sử dụng.", "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            flat = false;
            textFieldDiscountName.requestFocus();
            textFieldDiscountName.setText("");
        }

    }//GEN-LAST:event_textFieldDiscountNameKeyReleased

    private void textFieldDiscountStartDayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldDiscountStartDayKeyReleased
    }//GEN-LAST:event_textFieldDiscountStartDayKeyReleased

    private void textFieldDiscountEndDayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldDiscountEndDayKeyReleased
    }//GEN-LAST:event_textFieldDiscountEndDayKeyReleased

    private void textFieldContentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldContentKeyReleased
    }//GEN-LAST:event_textFieldContentKeyReleased

    private void textFieldDiscountStartDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDiscountStartDayFocusLost
        String begin = textFieldDiscountStartDay.getText().trim();

        if (begin.isEmpty()) {
            return;
        }

        if (!Tool.isValidDate(begin)) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            flat = false;
            textFieldDiscountStartDay.setText("");
            textFieldDiscountStartDay.requestFocus();
        } else if (!Tool.isStartDate(begin)) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải là ngày hiện tại hoặc trong tương lai", "Thông báo", JOptionPane.WARNING_MESSAGE);
            flat = false;
            textFieldDiscountStartDay.setText("");
            textFieldDiscountStartDay.requestFocus();
        }
    }//GEN-LAST:event_textFieldDiscountStartDayFocusLost

    private void textFieldDiscountEndDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDiscountEndDayFocusLost
        String end = textFieldDiscountEndDay.getText().trim();
        String begin = textFieldDiscountStartDay.getText().trim();

        if (end.isEmpty()) {
            return;
        }

        if (begin.isEmpty()) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Phải nhập ngày bắt đầu trước", "Thông báo", JOptionPane.WARNING_MESSAGE);
            flat = false;
            textFieldDiscountStartDay.requestFocus();
            textFieldDiscountEndDay.setText("");
            return;
        }

        if (!Tool.isValidDate(end)) {
            flat = true;
            JOptionPane.showMessageDialog(this, "ngày kết thúc không hơp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            flat = false;
            textFieldDiscountEndDay.setText("");
            textFieldDiscountEndDay.requestFocus();
        } else if (Tool.strToDate(begin).isAfter(Tool.strToDate(end))) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải sau ngày bắt đầu.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            flat = false;
            textFieldDiscountEndDay.setText("");
            textFieldDiscountEndDay.requestFocus();
        }

    }//GEN-LAST:event_textFieldDiscountEndDayFocusLost

    private void textFieldContentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldContentFocusLost
        String percentDiscount = textFieldContent.getText().trim();

        if (percentDiscount.isEmpty()) {
            return;
        }

        if (!Tool.isDiscount(percentDiscount)) {
            flat = true;
            JOptionPane.showMessageDialog(this, "Phần trăm giảm giá phải là một số thực(bé hơn 1 và lớn hơn hoặc bằng 0)", "Thông báo", JOptionPane.WARNING_MESSAGE);
            flat = false;
            textFieldContent.setText("");
            textFieldContent.requestFocus();
        }
    }//GEN-LAST:event_textFieldContentFocusLost

    private void jTableDiscountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableDiscountKeyPressed
        selectedRowIndex = jTableDiscount.getSelectedRow();
        int rowCount = jTableDiscount.getRowCount();

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP -> {
                if (selectedRowIndex > 0) {
                    jTableDiscount.changeSelection(selectedRowIndex--, 0, false, false);
                } else {
                }
            }
            case KeyEvent.VK_DOWN -> {
                if (selectedRowIndex == rowCount - 1) {
                } else {
                    jTableDiscount.changeSelection(selectedRowIndex++, 0, false, false);
                }
            }
        }
        showInfo();
    }//GEN-LAST:event_jTableDiscountKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonFix;
    private javax.swing.JButton buttonSearchDiscount;
    private javax.swing.JButton buttonShowAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDiscount;
    private javax.swing.JLabel labelPictureDiscount;
    private java.awt.ScrollPane scrollPane2;
    private javax.swing.JTextField textFieldContent;
    private javax.swing.JTextField textFieldDiscountEndDay;
    private javax.swing.JTextField textFieldDiscountID;
    private javax.swing.JTextField textFieldDiscountName;
    private javax.swing.JTextField textFieldDiscountStartDay;
    private javax.swing.JTextField textFieldSearch;
    // End of variables declaration//GEN-END:variables

}
