/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CreateImage;
import DTO.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author voota
 */
public final class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUIDangNhap
     */
    public LoginGUI() {
        this.setLocationRelativeTo(null);
        initComponents();
        editDisplay();
        // Thiết lập phím tắt cho nút buttonLogin
        InputMap inputMap = buttonLogin.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        textFieldPassWord.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "none");
        ActionMap actionMap = buttonLogin.getActionMap();
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "login");
        actionMap.put("login", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buttonLoginActionPerformed(e);
            }
        });
//        Sau khi nhập liệu tại textFieldAccount nhấn enter con trỏ sẽ di chuyển xuống textFieldPassWord
        textFieldAccount.addActionListener((ActionEvent e) -> {
            textFieldPassWord.requestFocusInWindow(); // Chuyển focus sang textfield 2
        });
        this.setSize(400, 300);
        this.setVisible(true);
    }
    
    public void editDisplay() {
        CreateImage cre = new CreateImage();
        cre.setBackgroundForPanel(panelLogin, "background2.png");
        textFieldAccount.setCaretColor(Color.white);  // Đổi màu dấu | trong textField
        textFieldPassWord.setCaretColor(Color.white);
        cre.changeColorButton(buttonLogin);
    }
    
    public javax.swing.JButton getButtonLogin() {
        return buttonLogin;
    }
    
    public javax.swing.JPanel getPanelLogin() {
        return panelLogin;
    }
    
    public javax.swing.JCheckBox getShowPassword() {
        return showPassword;
    }
    
    public javax.swing.JTextField getTextFieldAccount() {
        return textFieldAccount;
    }
    
    public javax.swing.JPasswordField getTextFieldPassWord() {
        return textFieldPassWord;
    }
    
    public void setUsername(String username) {
        textFieldAccount.setText(username);
    }
    
    public void setPassword(String password) {
        textFieldPassWord.setText(password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldAccount = new javax.swing.JTextField();
        textFieldPassWord = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        showPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng nhập");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tài khoản");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật khẩu");

        textFieldAccount.setForeground(new java.awt.Color(255, 255, 255));

        textFieldPassWord.setForeground(new java.awt.Color(255, 255, 255));
        textFieldPassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPassWordActionPerformed(evt);
            }
        });

        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Đăng nhập");
        buttonLogin.setBorder(new javax.swing.border.MatteBorder(null));
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginMouseClicked(evt);
            }
        });
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        showPassword.setText("Hiện mật khẩu");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addGap(0, 134, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldAccount)
                            .addComponent(textFieldPassWord)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showPassword))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        textFieldAccount.getAccessibleContext().setAccessibleName("jTextFieldTaiKhoan");
        textFieldPassWord.getAccessibleContext().setAccessibleName("");
        buttonLogin.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        ListEmployee listEp = new ListEmployee();
        ArrayList<EmployeeDTO> list = listEp.getListStillWork();
        String username = textFieldAccount.getText();
        String password = textFieldPassWord.getText();
        boolean flag = false;
        String employeeID = "";
        for (var item : list) {
            if (username.equals(item.getUsername()) && password.equals(item.getPassword())) {
                employeeID = item.getEmployeeID();
                flag = true;
                break;
            }
        }
        if (flag) {
            MainFrameGUI mainFrame = new MainFrameGUI(employeeID);
            mainFrame.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Thất bại. Tài khoản hoặc mật khẩu không đúng! Vui lòng thử lại");
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void textFieldPassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPassWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPassWordActionPerformed

    private void buttonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseClicked
    }//GEN-LAST:event_buttonLoginMouseClicked

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if (showPassword.isSelected()) {
            textFieldPassWord.setEchoChar((char) 0);
        } else {
            textFieldPassWord.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JTextField textFieldAccount;
    private javax.swing.JPasswordField textFieldPassWord;
    // End of variables declaration//GEN-END:variables
}
